export { default as Login } from "./Login";
export { default as Signup } from "./Signup";
export { default as Dashboard } from "./Dashboard";
import AddJewellery from "./AddJewellery";
export { AddJewellery };
export { default as JewelleryList } from "./JewelleryList";
export { default as EditJewellery } from "./EditJewellery";
export { default as Landing } from "./Landing";
export { default as TryOn } from "./TryOn";
export { default as Cart } from "./Cart";
export { default as Checkout } from "./Checkout";
export { default as ForgotPassword } from "./ForgotPassword";
export { default as ResetPassword } from "./ResetPassword";
export { default as PaymentSettings } from "./PaymentSettings";
export { default as JewelryDetails } from "./JewelryDetails";
export { default as LocationSettings } from "./LocationSettings";
export { default as About } from "./About";
export { default as Contact } from "./Contact";
export { default as Profile } from "./Profile";
export { default as Chat } from "./Chat";
export { default as PaymentCallback } from "./PaymentCallback";
